networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - ../storage/mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - ../storage/wordpress:/var/www/html
    networks:
      - inception
    depends_on: 
      - mariadb
    env_file:
      - .env
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - ../storage/wordpress:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    networks:
      - inception
    restart: always
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    restart: always
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    ports:
      - "20:20"
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    volumes:
      - ../storage/wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always