networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    volumes:
      - ./srcs/wordpress:/var/www/html
    networks:
      - inception
    depends_on: 
      - mariadb
    env_file:
      - .env
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    volumes:
      - ./srcs/wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
