networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - ../storage/mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - ../storage/wordpress:/var/www/html
    networks:
      - inception
    depends_on: 
      - mariadb
    env_file:
      - .env
    restart: always
    ports:
      - "8080:80"
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   volumes:
  #     - ./srcs/wordpress:/var/www/html
  #   ports:
  #     - "443:443"
  #   networks:
  #     - inception
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   restart: always
